### ISSUE TITLE
CLI support and publish package

### ISSUE THREAD

**Issue by Ahmedhamed77** [andrew-levy/jetpack-compose-react-native#10]
How could I use this package with cli project without expo?
also, why is the package not published? I believe when the package is published more people can test it 
I would love to use it in my app and start to add more native components to the package

**Comment by andrew-levy** [comment]
This relies on expo modules, so you'll need expo. It's the recommended way to build RN apps so I don't plan on removing that dependency. Also, there is still much to do to get everything working well and feature complete. Until then I'm not gona publish quite yet!

**Comment by andrew-levy** [comment]
But please feel free to contribute and test locally, then we can publish once it's in a stable state.
